{% set name = "atlassian-python-api" %}
{% set version = "3.33.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e0c44964d09ea6a155a97c08fffc122ca44bcfe40dd0d2dfdcac7be027dc878f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - deprecated
    - oauthlib
    - python >=2.7
    - requests
    - requests-oauthlib
    - six

test:
  imports:
    - atlassian
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/atlassian-api/atlassian-python-api
  summary: Python Atlassian REST API Wrapper
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dbast
    - epilif1017a
