{% set name = "atlassian-python-api" %}
{% set version = "4.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c5347e15c5a0a2ce987767c3428d112680fb5c4228f2f309009d9b01b5bea22e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - beautifulsoup4
    - deprecated
    - jmespath
    - lxml
    - oauthlib
    - requests >=2.8.1
    - requests-oauthlib
    - requests-kerberos 0.14.0
    - six

test:
  imports:
    - atlassian
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/atlassian-api/atlassian-python-api
  summary: Python Atlassian REST API Wrapper
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dbast
    - epilif1017a
